export const metadata = {
    title: 'Create A World | Piece',
    description: 'Generated by create next app',
}

export default function CreateLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
