export const metadata = {
    title: 'Creating a Piece | Piece',
    description: 'Generated by create next app',
}

export default function CreateLayout({
    children
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
