import '@/styles/globals.css'
import { Alike, Montserrat, Domine } from 'next/font/google'
import SupabaseProvider from './supabase-provider';
import DataProvider from './data-providers';
import NextTopLoader from 'nextjs-toploader';

const alike = Alike({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-alike'
})

const domine = Domine({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-domine'
})

const montserrat = Montserrat({
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-montserrat'
})


const meta = {
  title: 'New Age of Creative Writing | Piece',
  description: 'Generated by create next app',
  cardImage: '/og.png',
  robots: 'follow, index',
  favicon: '/favicon.ico',
  url: 'https://subscription-starter.vercel.app',
  type: 'website'
};

export const metadata = {
  title: meta.title,
  description: meta.description,
};

export const dynamic = 'force-dynamic'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className={`${alike.variable} ${montserrat.variable} ${domine.variable}`}>

      <body>
        <SupabaseProvider>
          <DataProvider>
            <main className="min-h-screen bg-background flex flex-col items-center">
              <NextTopLoader />
              {children}
            </main>
          </DataProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
