export const metadata = {
    title: 'Viewing a World | Piece',
    description: 'Generated by create next app',
}

export default async function CreateLayout({
    children,
}: {
    children: React.ReactNode,
}) {

    return (
        <>
            {children}
        </>
    )
}
